add ha-monitor service

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,14 +22,41 @@ jobs:
           mkdir -p .debpkg/usr/bin
           mkdir -p .debpkg/usr/share/wb-mqtt-confed/schemas
 
-          cp devices.conf        .debpkg/etc/wb-rules/wb-engine.devices.conf
-          cp wb-engine-rule.js   .debpkg/etc/wb-rules/wb-engine.js
-          cp wb-engine-module.js .debpkg/etc/wb-rules-modules/wb-engine.js
-          cp wb-engine-helper    .debpkg/usr/bin/wb-engine-helper
-          cp schema.json         .debpkg/usr/share/wb-mqtt-confed/schemas/wb-engine.schema.json
+          mkdir -p .debpkg/etc/systemd/ha-monitor.service.d
+
+          cp devices.conf                   .debpkg/etc/wb-rules/wb-engine.devices.conf
+          cp wb-engine-rule.js              .debpkg/etc/wb-rules/wb-engine.js
+          cp wb-engine-module.js            .debpkg/etc/wb-rules-modules/wb-engine.js
+          cp wb-engine-helper               .debpkg/usr/bin/wb-engine-helper
+          cp schema.json                    .debpkg/usr/share/wb-mqtt-confed/schemas/wb-engine.schema.json
+
+          cp ha-monitor                     .debpkg/usr/bin/ha-monitor 
+          chmod +x .debpkg/usr/bin/ha-monitor
+          cp ha-monitor.service             .debpkg/etc/systemd/system/ha-monitor.service
+          cp ha-monitor.service.custom.conf .debpkg/etc/systemd/system/ha-monitor.service.d/custom.conf
 
           mkdir -p .debpkg/DEBIAN
-          echo -e "touch /etc/wb-rules/wb-engine.conf" > .debpkg/DEBIAN/postinst
+
+          echo -e "#!/bin/sh" > .debpkg/DEBIAN/postinst
+          echo -e "touch /etc/wb-rules/wb-engine.conf" >> .debpkg/DEBIAN/postinst
+          SERVICE_NAME=ha-monitor.service
+          echo -e "
+          if command -v systemctl >/dev/null 2>&1; then
+              echo \"Reloading systemd daemon...\"
+              systemctl daemon-reexec || true
+              systemctl daemon-reload || true
+
+              echo \"Enabling $SERVICE_NAME to start on boot...\"
+              systemctl enable \"$SERVICE_NAME\" || true
+
+              echo \"Starting $SERVICE_NAME...\"
+              systemctl start \"$SERVICE_NAME\" || true
+          else
+              echo \"Systemd not found; skipping service setup.\"
+          fi
+
+          exit 0"  >> .debpkg/DEBIAN/postinst
+          
           chmod +x .debpkg/DEBIAN/postinst
       - name: Build armhf
         uses: jiro4989/build-deb-action@v3
